services:
  pbp-jupyter:
    container_name: pbp-jupyter
    image: ${PBP_IMAGE}
    ports: ['8888:8888']
    volumes: [
      '/home/carueda/pbp_workspace:/opt/pbp/workspace',
    ]
    restart: unless-stopped
